# KubeArmor is an open source software that enables you to protect your cloud workload at run-time.
# To learn more about KubeArmor visit: 
# https://www.accuknox.com/kubearmor/ 

apiVersion: security.kubearmor.com/v1
kind: KubeArmorPolicy
metadata:
  name: ksp-defense-evasion-deobfuscate
  namespace: default  #change with your namespace
spec:
  tags: ["MITRE","system","K8s","base32"]
  message: "AUDITING SHARED AND GROUP ACCOUNT CREDENTIALS CHANGE"
  selector:
    matchLabels:
      app: testpod #change with your own label
  process:
    matchPaths:
      - path: /usr/bin/base32
      - path: /usr/bin/base16
      - path: /usr/bin/base32plain
      - path: /usr/bin/base32hex
    action: Audit
    severity: 3
